language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source --no-interaction

after_success:
  - travis_retry php vendor/bin/coveralls

script: vendor/bin/phpunit